-- Посада.
CREATE TABLE "Positions"(
ID SERIAL NOT NULL UNIQUE PRIMARY KEY,
Name_Position VARCHAR(55) NOT NULL UNIQUE,
Salary INT NOT NULL
)

-- Клієнти.
CREATE TABLE "Clients"(
ID SERIAL NOT NULL UNIQUE PRIMARY KEY,
Surname VARCHAR(55) NOT NULL,
Name VARCHAR(55) NOT NULL
)

-- Адміністративні контакти.
CREATE TABLE "Subsidiary_contacts"(
ID SERIAL NOT NULL UNIQUE PRIMARY KEY,
Name VARCHAR(55) NOT NULL,
Phone VARCHAR(55) NOT NULL,
Hours VARCHAR(55)
)

-- Постачальники.
CREATE TABLE "Suppliers"( -- Поставщики
ID SERIAL NOT NULL UNIQUE,
Name VARCHAR(55) NOT NULL, -- имя поставщика
Country VARCHAR(55) NOT NULL, -- Cтрана
PRIMARY KEY(Name, Country),
UNIQUE(Name, Country)
)

-- Фармацевтична група.
CREATE TABLE "Pharmacological_Group"(
ID SERIAL NOT NULL UNIQUE PRIMARY KEY,
Name VARCHAR(55) NOT NULL,
Description VARCHAR(2048)
)

-- Інструкції.
CREATE TABLE "Instructions"(
ID SERIAL NOT NULL UNIQUE PRIMARY KEY,
Age INT NOT NULL,
Once_Day INT NOT NULL,
Restrictions VARCHAR(2048)
)


-- Телефон.
CREATE TABLE "Phones"(
ID INT UNIQUE PRIMARY KEY REFERENCES "Pharmacy" (ID_PhonePhone) ON DELETE CASCADE ON UPDATE CASCADE,
Phone_number(Main) VARCHAR(55) NOT NULL,
Phone_number(Mobile) VARCHAR(55),
Phone_number(Backup) VARCHAR(55) 
)

-- Співробітники.
CREATE TABLE "Employees"(
ID SERIAL NOT NULL UNIQUE PRIMARY KEY,
First_Name VARCHAR(55) NOT NULL,
Name VARCHAR(55) NOT NULL,
Surname VARCHAR(55) NOT NULL,
ID_Position INT NOT NULL REFERENCES "Positions" (ID) ON DELETE CASCADE ON UPDATE CASCADE
)

-- Товар.
CREATE TABLE "Drugs"(
ID SERIAL NOT NULL UNIQUE PRIMARY KEY,
ID_Supplier INT  NOT NULL REFERENCES "Suppliers" (ID) ON DELETE CASCADE ON UPDATE CASCADE,
ID_Farm_Group INT  NOT NULL REFERENCES "Pharmacological_Group" (ID) ON DELETE CASCADE ON UPDATE CASCADE,
ID_Instructions INT NOT NULL REFERENCES "Instructions" (ID) ON DELETE CASCADE ON UPDATE CASCADE,
Name VARCHAR(55),
Recipe BIT,
Price INT
)

-- Аптека.
CREATE TABLE "Pharmacy"(
ID SERIAL NOT NULL UNIQUE PRIMARY KEY,
ID_Director INT NOT NULL UNIQUE REFERENCES "Employees" (ID) ON DELETE CASCADE,
ID_Phone INT NOT NULL UNIQUE REFERENCES "Phones" (ID) ON DELETE CASCADE ON UPDATE CASCADE,
ID_Subsidiary_contacts INT NOT NULL REFERENCES "Subsidiary_contacts" (ID) ON DELETE CASCADE ON UPDATE CASCADE,
Name VARCHAR(55) NOT NULL,
Address VARCHAR(55) NOT NULL,
Hours VARCHAR(55) NOT NULL
)


-- Відгуки клієнтів.
CREATE TABLE "Wishes"(
ID SERIAL NOT NULL UNIQUE PRIMARY KEY,
ID_Pharmacy INT NOT NULL REFERENCES "Pharmacy" (ID) ON DELETE CASCADE ON UPDATE CASCADE,
ID_Clients INT NOT NULL REFERENCES "Clients" (ID) ON DELETE CASCADE ON UPDATE CASCADE,
Wish VARCHAR(2048)
)

-- Чек.
CREATE TABLE "Receipts"(
ID SERIAL NOT NULL UNIQUE PRIMARY KEY,
ID_Pharmacy INT NOT NULL REFERENCES "Pharmacy" (ID) ON DELETE CASCADE ON UPDATE CASCADE ,
ID_Client INT NOT NULL REFERENCES "Clients" (ID) ON DELETE CASCADE ON UPDATE CASCADE,
ID_Product INT NOT NULL REFERENCES "Drugs" (ID) ON DELETE CASCADE ON UPDATE CASCADE,
"Date" DATE NOT NULL,
Sum INT NOT NULL
)

-- Знижка.
CREATE TABLE "Discounts"(
ID SERIAL NOT NULL UNIQUE PRIMARY KEY,
ID_Pharmacy INT NOT NULL REFERENCES "Pharmacy" (ID) ON DELETE CASCADE ON UPDATE CASCADE,
ID_Product INT NOT NULL REFERENCES "Drugs" (ID) ON DELETE CASCADE ON UPDATE CASCADE,
Discount_Percentage INT NOT NULL,
Date_Start DATE NOT NULL,
Date_Finish DATE NOT NULL
)

-- Склад.
CREATE TABLE "Storage" (
ID SERIAL NOT NULL UNIQUE PRIMARY KEY,
ID_Pharmacy INT NOT NULL REFERENCES "Pharmacy" (ID) ON DELETE CASCADE ON UPDATE CASCADE,
ID_Product INT  NOT NULL REFERENCES "Drugs" (ID) ON DELETE CASCADE ON UPDATE CASCADE,
Serial_number VARCHAR(55) NOT NULL UNIQUE,
Quantity INT NOT NULL,
Expiration_date DATE NOT NULL
)

-- Реклама.
CREATE TABLE "Adversting"(
ID SERIAL NOT NULL UNIQUE PRIMARY KEY,
ID_Pharmacy INT NOT NULL REFERENCES "Pharmacy" (ID) ON DELETE CASCADE ON UPDATE CASCADE,
ID_Product INT NOT NULL REFERENCES "Drugs" (ID) ON DELETE CASCADE ON UPDATE CASCADE,
Budget INT NOT NULL,
Date_Start DATE NOT NULL,
Date_Finish DATE NOT NULL
)