CREATE TABLE "Positions"(
ID SERIAL NOT NULL UNIQUE PRIMARY KEY,
Name_Position VARCHAR(55) NOT NULL UNIQUE,
Salary INT NOT NULL
)

CREATE TABLE "Clients"(
ID SERIAL NOT NULL UNIQUE PRIMARY KEY,
Surname VARCHAR(55) NOT NULL,
Name VARCHAR(55) NOT NULL
)

CREATE TABLE "Suppliers"( -- Поставщики
ID SERIAL NOT NULL UNIQUE,
Name VARCHAR(55) NOT NULL, -- имя поставщика
Country VARCHAR(55) NOT NULL, -- Cтрана
PRIMARY KEY(Name, Country),
UNIQUE(Name, Country)
)


CREATE TABLE "Pharmacological_Group"(
ID SERIAL NOT NULL UNIQUE PRIMARY KEY,
Name VARCHAR(55)
)

CREATE TABLE "Instructions"(
ID SERIAL NOT NULL UNIQUE PRIMARY KEY,
Age INT NOT NULL,
Once_Day INT NOT NULL,
Restrictions VARCHAR(2048)
)

CREATE TABLE "Employees"(
ID SERIAL NOT NULL UNIQUE PRIMARY KEY,
First_Name VARCHAR(55) NOT NULL,
Name VARCHAR(55) NOT NULL,
Surname VARCHAR(55) NOT NULL,
ID_Position INT NOT NULL REFERENCES "Positions" (ID) ON DELETE CASCADE ON UPDATE CASCADE
)


CREATE TABLE "Drugs"(
ID SERIAL NOT NULL UNIQUE PRIMARY KEY,
ID_Supplier INT  NOT NULL REFERENCES "Suppliers" (ID) ON DELETE CASCADE ON UPDATE CASCADE,
ID_Farm_Group INT  NOT NULL REFERENCES "Pharmacological_Group" (ID) ON DELETE CASCADE ON UPDATE CASCADE,
ID_Instructions INT NOT NULL REFERENCES "Instructions" (ID) ON DELETE CASCADE ON UPDATE CASCADE,
Name VARCHAR(55),
Recipe BIT,
Price INT
)




CREATE TABLE "Pharmacy"(
ID SERIAL NOT NULL UNIQUE PRIMARY KEY,
ID_Director INT NOT NULL UNIQUE REFERENCES "Employees" (ID) ON DELETE CASCADE,
Phone VARCHAR(55) NOT NULL UNIQUE,
Name VARCHAR(55) NOT NULL,
Address VARCHAR(55) NOT NULL,
Hours VARCHAR(55) NOT NULL
)


CREATE TABLE "Phones"(
ID SERIAL NOT NULL UNIQUE PRIMARY KEY,
Phone VARCHAR(55) NOT NULL REFERENCES "Pharmacy" (Phone) ON DELETE CASCADE ON UPDATE CASCADE
)

CREATE TABLE "Wishes"(
ID SERIAL NOT NULL UNIQUE PRIMARY KEY,
ID_Pharmacy INT NOT NULL REFERENCES "Pharmacy" (ID) ON DELETE CASCADE ON UPDATE CASCADE,
ID_Clients INT NOT NULL REFERENCES "Clients" (ID) ON DELETE CASCADE ON UPDATE CASCADE,
Wish VARCHAR(2048)
)

CREATE TABLE "Receipts"(
ID SERIAL NOT NULL UNIQUE PRIMARY KEY,
ID_Pharmacy INT NOT NULL REFERENCES "Pharmacy" (ID) ON DELETE CASCADE ON UPDATE CASCADE ,
ID_Client INT NOT NULL REFERENCES "Clients" (ID) ON DELETE CASCADE ON UPDATE CASCADE,
ID_Product INT NOT NULL REFERENCES "Drugs" (ID) ON DELETE CASCADE ON UPDATE CASCADE,
"Date" DATE NOT NULL,
Sum INT NOT NULL
)


CREATE TABLE "Discounts"(
ID SERIAL NOT NULL UNIQUE PRIMARY KEY,
ID_Pharmacy INT NOT NULL REFERENCES "Pharmacy" (ID) ON DELETE CASCADE ON UPDATE CASCADE,
ID_Product INT NOT NULL REFERENCES "Drugs" (ID) ON DELETE CASCADE ON UPDATE CASCADE,
Discount_Percentage INT NOT NULL,
Date_Start DATE NOT NULL,
Date_Finish DATE NOT NULL
)